# Generated by Django 4.0.1 on 2022-01-28 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
    ]
