# Generated by Django 4.0.1 on 2022-02-10 05:44

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_news_category_alter_notification_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(max_length=9, unique=True)),
                ('image', models.ImageField(upload_to=core.models.Plate.upload_too, verbose_name='Image')),
                ('color', models.CharField(max_length=100)),
                ('fuel', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('model', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
