# Generated by Django 4.0.1 on 2022-02-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plate',
            name='image',
        ),
    ]
